# This file was generated by GoReleaser. DO NOT EDIT.
cask "omatty" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "e82f2b88bf3f46d85e294edd8d6e898f5b832873ef64d52a78f7ef8a36ceaf38"
      url "https://github.com/WilsonSousajr/omatty/releases/download/v#{version}/omatty_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "307021a16d91f9c745a9d5d779a99f78fb481b21f802ea0c011f2ca71c69f92b"
      url "https://github.com/WilsonSousajr/omatty/releases/download/v#{version}/omatty_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e4b75d195773b144c1cf0cc85332887eae997183177fba59ca615433203f74e7"
      url "https://github.com/WilsonSousajr/omatty/releases/download/v#{version}/omatty_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b6929f3fe2903554706a4b828126fea38cbe811e5536475b9783ea1fb078e0f9"
      url "https://github.com/WilsonSousajr/omatty/releases/download/v#{version}/omatty_#{version}_linux_amd64.tar.gz"
    end
  end

  name "omatty"
  desc "Terminal ADE: multiple projects and parallel Claude Code sessions in one TUI"
  homepage "https://github.com/WilsonSousajr/omatty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "omatty"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/omatty"]
    end
  end

  # No zap stanza required
end
