# This file was generated by GoReleaser. DO NOT EDIT.
cask "omatty" do
  version "0.10.0"

  on_macos do
    on_arm do
      sha256 "79486a0072016bfdead88915824b366f96852a0a93f4961cccbbf9dc1e15e839"
      url "https://github.com/WilsonSousajr/omatty/releases/download/v#{version}/omatty_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ca4e4cc367459269fbf96399446fe0740f0ce66ee128f741e9d99ea2803763fa"
      url "https://github.com/WilsonSousajr/omatty/releases/download/v#{version}/omatty_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2151741afd81bdcd9be6c6c984e27b1fda9cc3ee59bd3443300b36333eb5764b"
      url "https://github.com/WilsonSousajr/omatty/releases/download/v#{version}/omatty_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "925bd22f753d77962e6b284b00ec247975a75f2891f6140c482ae35ba7970ad8"
      url "https://github.com/WilsonSousajr/omatty/releases/download/v#{version}/omatty_#{version}_linux_amd64.tar.gz"
    end
  end

  name "omatty"
  desc "Terminal ADE: multiple projects and parallel Claude Code sessions in one TUI"
  homepage "https://github.com/WilsonSousajr/omatty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "omatty"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/omatty"], must_succeed: false
    end
  end

  # No zap stanza required
end
