# This file was generated by GoReleaser. DO NOT EDIT.
cask "omatty" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "77719917e3aebc78db645d72bdda0b172a5c9d5cbe3d7e328edbf418eaa984c1"
      url "https://github.com/WilsonSousajr/omatty/releases/download/v#{version}/omatty_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "684ebf2212281784ce62b9a2316ca2aed33b6e081df31655575e18c136a4ac7e"
      url "https://github.com/WilsonSousajr/omatty/releases/download/v#{version}/omatty_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "340b6d5b3cbe01ae667041fd5fa60f271a3253feda2a0d3c087162c115a351ae"
      url "https://github.com/WilsonSousajr/omatty/releases/download/v#{version}/omatty_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "54d1942e5b3e01829034ba8df0d5fd3a3c7fd07594acd92bd53b5a0c971c41f2"
      url "https://github.com/WilsonSousajr/omatty/releases/download/v#{version}/omatty_#{version}_linux_amd64.tar.gz"
    end
  end

  name "omatty"
  desc "Terminal ADE: multiple projects and parallel Claude Code sessions in one TUI"
  homepage "https://github.com/WilsonSousajr/omatty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "omatty"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/omatty"]
    end
  end

  # No zap stanza required
end
